#spring profiles
spring:
    #http encoding
    http:
        encoding:
          charset: UTF-8
          enable: true
          force: true
   #profiles
    profiles:
      active: dev
#      active: prod


